import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Galib E Shop</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />

                {/* fontAwesome */}
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
                <link
                    href="https://fonts.googleapis.com/css2?family=Poppins:ital@1&display=swap"
                    rel="stylesheet"
                />
            </Head>

            <h1>Galib E Shop</h1>
            <h1 className="text-3xl font-bold underline text-sky-500">Hello world!</h1>
        </div>
    );
}
